export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/limited-time-discount/index",
    "pages/purchased-courses/index",
    "pages/personal/index",
    "pages/search/index",
    "pages/lesson-detail/index",
    "pages/directory/index",
    "pages/teacher-course/index",
    // "components/ensure/index",
    // "components/order-detail/index",
    // "components/address-select/index",
    "pages/course-classification/index",
    "pages/evaluate-detail/index",
    "pages/order/index",
    "pages/browsing-history/index",
    "pages/message/index",
    "pages/address/index",
    "pages/address-create/index",
    "pages/address-no-empty/index",
    "pages/coupon/index",
    "pages/coupon-unuse/index",
    "pages/coupon-used/index",
    "pages/coupon-expired/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
});
