export default defineAppConfig({
  entryPagePath: "pages/teacher-course/index",
  pages: [
    "pages/index/index",
    "pages/limited-time-discount/index",
    "pages/courses-purchased/index",
    "pages/personal/index",
    "pages/search/index",
    "pages/lesson-detail/index",
    "pages/directory/index",
    "pages/teacher-course/index",
    // "components/ensure/index",
    // "components/order-detail/index",
    // "components/address-select/index",
    "pages/course-classification/index",
    "pages/evaluate-detail/index",
    "pages/order/index",
    "pages/browsing-history/index",
    "pages/message/index",
    "pages/address/index",
    "pages/address-create/index",
    "pages/address-no-empty/index",
    "pages/coupon/index",
    "pages/coupon-unuse/index",
    "pages/coupon-used/index",
    "pages/coupon-expired/index",
    "pages/seckill/index",
    "pages/seckill-list/index",
    "pages/seckill-course-detail/index",
    "pages/chat/index",
    "pages/order-payable/index",
    "pages/order-payed/index",
    "pages/order-detail/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
  tabBar: {
    color: "#7A7E83",
    selectedColor: "#3cc51f",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/index/index",
        text: "首页",
        // iconPath: "assets/images/tabbar/home.png",
        iconPath: "assets/images/tabbar/home-selected.png",
        selectedIconPath: "assets/images/tabbar/home-selected.png",
      },
      {
        pagePath: "pages/courses-purchased/index",
        text: "已购课程",
        // iconPath: "assets/images/tabbar/category.png",
        iconPath:
          "https://img12.360buyimg.com/ling/jfs/t1/227750/14/17403/1649/663ae599F948e4aff/aa8155f1c4153fa4.png",
        selectedIconPath:
          "https://img12.360buyimg.com/ling/jfs/t1/227750/14/17403/1649/663ae599F948e4aff/aa8155f1c4153fa4.png",
      },
      {
        pagePath: "pages/personal/index",
        text: "个人中心",
        // iconPath: "assets/images/tabbar/category.png",
        iconPath:
          "https://img30.360buyimg.com/ling/jfs/t1/175288/21/40525/2126/663ae599F348593af/ac6054954e4d3a09.png",
        selectedIconPath:
          "https://img30.360buyimg.com/ling/jfs/t1/175288/21/40525/2126/663ae599F348593af/ac6054954e4d3a09.png",
      },
    ],
  },
});
